### ISSUE TITLE
Package review

### ISSUE THREAD

**Issue by pat-s** [henrifnk/mlr3learners.C50#1]
- Please respect our [style guide](https://github.com/mlr-org/mlr3/wiki/Style-Guide)
- Arg ` na.action` is missing (predict)
- Isn't the name C5.0 and not C50? ->  "classif.C50"
- Arg `subset` has the wrong default
- Arg `bands` has the wrong default
- Always specify the default as the first argument of a param
- update README

@henrifnk

**Comment by pat-s** [comment]
Please recheck the just updated instructions in the mlr3learners template repo: https://github.com/mlr-org/mlr3learners.template.

**Comment by henrifnk** [comment]
Hope everything is integrated now
@pat-s

**Comment by pat-s** [comment]
Thanks! Please check the following points:

- [x] Check Remotes: section in DESCRIPTION
- [x] run `usethis::use_tidy_description()`
- [x] check `NEWS.md`
- [x] Fix CI badge
- [x] set version to "dev"
- [x] rename package & repo
- [x] replace all `<-` with `=`
- [x] add learner to https://github.com/mlr-org/mlr3learners/wiki (in progress)

**Comment by henrifnk** [comment]
I checked all the points I could fix so far, concerning the remaining points:
1. I guess the CI batches will work once I tranfer my repo to [mlr3learners](https://github.com/mlr3learners)?

2. > rename package & repo

 do you want me to tranfer the Repo to the [mlr3learners](https://github.com/mlr3learners) orga by that? 
(i.e.: *mlr3learners/mlr3learners.C50*)

3. As far as I can see I have no rights to edit the [Wiki](https://github.com/mlr-org/mlr3learners/wiki#in-progress)

**Comment by pat-s** [comment]
> do you want me to tranfer the Repo to the mlr3learners orga by that?
> (i.e.: mlr3learners/mlr3learners.C50)

Ah the package name is actually C50 so all is fine.
And yes, you can transfer it to the mlr3learners org.

> As far as I can see I have no rights to edit the Wiki

Now you have :)

> I guess the CI batches will work once I tranfer my repo to mlr3learners?

Correct, looks good!

**Comment by henrifnk** [comment]
Top, Thanks
Learner is transfered
